# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax
name: 'Setup dotsecenv'
description: 'Download and verify dotsecenv release binaries, or build from source'
author: 'dotsecenv'

branding:
  icon: 'lock'
  color: 'green'

inputs:
  build-from-source:
    description: 'Build from source instead of using pre-built release binaries'
    required: false
    default: 'false'
  verify-provenance:
    description: 'Verify attestations, checksums, and GPG signatures (ignored if build-from-source is true)'
    required: false
    default: 'true'

outputs:
  version:
    description: 'The version of dotsecenv that was installed'
    value: ${{ steps.release-tag.outputs.version }}
  binary-path:
    description: 'Full path to the installed binary'
    value: ${{ steps.install-release.outputs.binary-path || steps.install-source.outputs.binary-path }}

runs:
  using: 'composite'
  steps:
    # ============================================
    # Detect release tag
    # ============================================
    - name: Detect semver tags
      id: release-tag
      shell: bash
      run: |
        TAGS=$(git tag --points-at HEAD 2>/dev/null | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V || true)

        if [[ -z "$TAGS" ]]; then
          echo "is-release=false" >> $GITHUB_OUTPUT
          echo "version=$(git describe --tags --always --dirty 2>/dev/null || echo dev)" >> $GITHUB_OUTPUT
        else
          echo "is-release=true" >> $GITHUB_OUTPUT
          echo "version=$(echo "$TAGS" | tail -1)" >> $GITHUB_OUTPUT
        fi

    - name: Fail if no tags and build-from-source is false
      if: steps.release-tag.outputs.is-release == 'false' && inputs.build-from-source != 'true'
      shell: bash
      run: |
        echo "::error::Release tag not found on the current commit. Either tag this commit (e.g., v1.0.0) or set build-from-source: true"
        exit 1

    # ===========================================================
    # When downloading releases, determine OS and architecture
    # ===========================================================
    - name: Determine architecture
      id: arch
      if: steps.release-tag.outputs.is-release == 'true'
      shell: bash
      run: |
        case "${{ runner.os }}" in
          Linux)  echo "os=Linux" >> $GITHUB_OUTPUT ;;
          macOS)  echo "os=Darwin" >> $GITHUB_OUTPUT ;;
          *)      echo "::error::Unsupported OS: ${{ runner.os }}"; exit 1 ;;
        esac
        case "${{ runner.arch }}" in
          X64)    echo "arch=x86_64" >> $GITHUB_OUTPUT ;;
          ARM64)  echo "arch=arm64" >> $GITHUB_OUTPUT ;;
          *)      echo "::error::Unsupported arch: ${{ runner.arch }}"; exit 1 ;;
        esac

    - name: Download release
      id: download
      if: steps.release-tag.outputs.is-release == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        VERSION="${{ steps.release-tag.outputs.version }}"
        ARCHIVE="dotsecenv_${VERSION#v}_${{ steps.arch.outputs.os }}_${{ steps.arch.outputs.arch }}.tar.gz"
        DEST="${{ runner.temp }}/dotsecenv-download"
        mkdir -p "$DEST"

        gh release download "$VERSION" --repo dotsecenv/dotsecenv --pattern "$ARCHIVE" --pattern "checksums.txt*" --dir "$DEST"

        echo "dir=$DEST" >> $GITHUB_OUTPUT
        echo "archive=$ARCHIVE" >> $GITHUB_OUTPUT

    - name: Import GPG key
      if: steps.release-tag.outputs.is-release == 'true' && inputs.verify-provenance == 'true'
      shell: bash
      run: |
        curl -fsSL http://get.dotsecenv.com/key.asc | gpg --import

    - name: Verify GPG signature
      if: steps.release-tag.outputs.is-release == 'true' && inputs.verify-provenance == 'true'
      shell: bash
      working-directory: ${{ steps.download.outputs.dir }}
      run: gpg --verify checksums.txt.sig checksums.txt

    - name: Verify checksum
      if: steps.release-tag.outputs.is-release == 'true' && inputs.verify-provenance == 'true'
      shell: bash
      working-directory: ${{ steps.download.outputs.dir }}
      run: grep "${{ steps.download.outputs.archive }}" checksums.txt | sha256sum -c -

    - name: Verify attestation
      if: steps.release-tag.outputs.is-release == 'true' && inputs.verify-provenance == 'true'
      shell: bash
      working-directory: ${{ steps.download.outputs.dir }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh attestation verify "${{ steps.download.outputs.archive }}" --repo dotsecenv/dotsecenv

    - name: Install release binary
      id: install-release
      if: steps.release-tag.outputs.is-release == 'true'
      shell: bash
      run: |
        INSTALL_DIR="${{ runner.temp }}/dotsecenv-bin"
        mkdir -p "$INSTALL_DIR"
        tar -xzf "${{ steps.download.outputs.dir }}/${{ steps.download.outputs.archive }}" -C "$INSTALL_DIR"
        chmod +x "$INSTALL_DIR/dotsecenv"
        "$INSTALL_DIR/dotsecenv" version
        echo "$INSTALL_DIR" >> $GITHUB_PATH
        echo "binary-path=$INSTALL_DIR/dotsecenv" >> $GITHUB_OUTPUT

    # ============================================
    # Build from source path (when no tags)
    # ============================================
    - name: Set up Go
      if: steps.release-tag.outputs.is-release == 'false' && inputs.build-from-source == 'true'
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Build from source
      if: steps.release-tag.outputs.is-release == 'false' && inputs.build-from-source == 'true'
      shell: bash
      run: make build

    - name: Install source binary
      id: install-source
      if: steps.release-tag.outputs.is-release == 'false' && inputs.build-from-source == 'true'
      shell: bash
      run: |
        INSTALL_DIR="${{ runner.temp }}/dotsecenv-bin"
        mkdir -p "$INSTALL_DIR"
        cp bin/dotsecenv "$INSTALL_DIR/dotsecenv"
        chmod +x "$INSTALL_DIR/dotsecenv"
        "$INSTALL_DIR/dotsecenv" version
        echo "$INSTALL_DIR" >> $GITHUB_PATH
        echo "binary-path=$INSTALL_DIR/dotsecenv" >> $GITHUB_OUTPUT
