# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax
name: 'Setup dotsecenv'
description: 'Download and verify dotsecenv release binaries, or build from source'
author: 'dotsecenv'

branding:
  icon: 'lock'
  color: 'green'

inputs:
  version:
    description: 'Version to install (e.g., v1.2.3, or "latest" for most recent release)'
    required: false
    default: 'latest'
  build-from-source:
    description: 'Build from source instead of using pre-built release binaries'
    required: false
    default: 'false'
  verify-provenance:
    description: 'Verify attestations, checksums, and GPG signatures (ignored if build-from-source is true)'
    required: false
    default: 'true'
  init-config:
    description: 'Arguments for "dotsecenv init config". Set to empty string to run with defaults, or provide flags (e.g., "--strict --login FINGERPRINT"). Leave as "skip" to not run.'
    required: false
    default: 'skip'

outputs:
  version:
    description: 'The version of dotsecenv that was installed'
    value: ${{ steps.resolve-version.outputs.version }}
  binary-path:
    description: 'Full path to the installed binary'
    value: ${{ steps.install-release.outputs.binary-path || steps.install-source.outputs.binary-path }}

runs:
  using: 'composite'
  steps:
    # ============================================
    # Resolve version
    # ============================================
    - name: Resolve version
      id: resolve-version
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        if [[ "${{ inputs.version }}" == "latest" ]]; then
          VERSION=$(gh release view --repo dotsecenv/dotsecenv --json tagName -q .tagName)
          echo "Resolved latest version: $VERSION"
        else
          VERSION="${{ inputs.version }}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    # ===========================================================
    # Download release
    # ===========================================================
    - name: Determine architecture
      id: arch
      if: inputs.build-from-source != 'true'
      shell: bash
      run: |
        case "${{ runner.os }}" in
          Linux)  echo "os=Linux" >> $GITHUB_OUTPUT ;;
          macOS)  echo "os=Darwin" >> $GITHUB_OUTPUT ;;
          *)      echo "::error::Unsupported OS: ${{ runner.os }}"; exit 1 ;;
        esac
        case "${{ runner.arch }}" in
          X64)    echo "arch=x86_64" >> $GITHUB_OUTPUT ;;
          ARM64)  echo "arch=arm64" >> $GITHUB_OUTPUT ;;
          *)      echo "::error::Unsupported arch: ${{ runner.arch }}"; exit 1 ;;
        esac

    - name: Download release
      id: download
      if: inputs.build-from-source != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        VERSION="${{ steps.resolve-version.outputs.version }}"
        ARCHIVE="dotsecenv_${VERSION#v}_${{ steps.arch.outputs.os }}_${{ steps.arch.outputs.arch }}.tar.gz"
        DEST="${{ runner.temp }}/dotsecenv-download"
        mkdir -p "$DEST"

        gh release download "$VERSION" --repo dotsecenv/dotsecenv --pattern "$ARCHIVE" --pattern "checksums.txt*" --dir "$DEST"

        echo "dir=$DEST" >> $GITHUB_OUTPUT
        echo "archive=$ARCHIVE" >> $GITHUB_OUTPUT

    - name: Import GPG key
      if: inputs.build-from-source != 'true' && inputs.verify-provenance == 'true'
      shell: bash
      run: |
        curl -fsSL http://get.dotsecenv.com/key.asc | gpg --import

    - name: Verify GPG signature
      if: inputs.build-from-source != 'true' && inputs.verify-provenance == 'true'
      shell: bash
      working-directory: ${{ steps.download.outputs.dir }}
      run: gpg --verify checksums.txt.sig checksums.txt

    - name: Verify checksum
      if: inputs.build-from-source != 'true' && inputs.verify-provenance == 'true'
      shell: bash
      working-directory: ${{ steps.download.outputs.dir }}
      run: grep "${{ steps.download.outputs.archive }}$" checksums.txt | sha256sum -c -

    - name: Verify attestation
      if: inputs.build-from-source != 'true' && inputs.verify-provenance == 'true'
      shell: bash
      working-directory: ${{ steps.download.outputs.dir }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh attestation verify "${{ steps.download.outputs.archive }}" --repo dotsecenv/dotsecenv

    - name: Install release binary
      id: install-release
      if: inputs.build-from-source != 'true'
      shell: bash
      run: |
        INSTALL_DIR="${{ runner.temp }}/dotsecenv-bin"
        mkdir -p "$INSTALL_DIR"
        tar -xzf "${{ steps.download.outputs.dir }}/${{ steps.download.outputs.archive }}" -C "$INSTALL_DIR"
        chmod +x "$INSTALL_DIR/dotsecenv"
        "$INSTALL_DIR/dotsecenv" version
        echo "$INSTALL_DIR" >> $GITHUB_PATH
        echo "binary-path=$INSTALL_DIR/dotsecenv" >> $GITHUB_OUTPUT

    # ============================================
    # Build from source path
    # ============================================
    - name: Checkout the source code
      id: checkout
      if: inputs.build-from-source == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        VERSION="${{ steps.resolve-version.outputs.version }}"
        DEST="${{ runner.temp }}/dotsecenv-download"
        git clone --depth 1 --branch "$VERSION" https://github.com/dotsecenv/dotsecenv.git "$DEST"
        echo "dir=$DEST" >> $GITHUB_OUTPUT

    - name: Set up Go
      if: inputs.build-from-source == 'true'
      uses: actions/setup-go@v6
      with:
        cache-dependency-path: "${{ steps.checkout.outputs.dir }}/go.sum"
        go-version-file: "${{ steps.checkout.outputs.dir }}/go.mod"

    - name: Build from source
      if: inputs.build-from-source == 'true'
      working-directory: ${{ steps.checkout.outputs.dir }}
      shell: bash
      run: |
        make build

    - name: Install source binary
      id: install-source
      if: inputs.build-from-source == 'true'
      working-directory: ${{ steps.checkout.outputs.dir }}
      shell: bash
      run: |
        INSTALL_DIR="${{ runner.temp }}/dotsecenv-bin"
        mkdir -p "$INSTALL_DIR"
        cp bin/dotsecenv "$INSTALL_DIR/dotsecenv"
        chmod +x "$INSTALL_DIR/dotsecenv"
        "$INSTALL_DIR/dotsecenv" version
        echo "$INSTALL_DIR" >> $GITHUB_PATH
        echo "binary-path=$INSTALL_DIR/dotsecenv" >> $GITHUB_OUTPUT

    # ============================================
    # Initialize config (optional)
    # ============================================
    - name: Initialize config
      if: inputs.init-config != 'skip'
      shell: bash
      run: |
        dotsecenv init config ${{ inputs.init-config }}
