name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the form below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `dotsecenv ...`
        2. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: What happened instead?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: dotsecenv Version
      description: Output of `dotsecenv version`
      placeholder: "dotsecenv version v0.1.0 (commit: abc1234)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux (Debian/Ubuntu)
        - Linux (RHEL/CentOS/Fedora)
        - Linux (Arch)
        - Linux (Other)
        - Windows
    validations:
      required: true

  - type: dropdown
    id: arch
    attributes:
      label: Architecture
      options:
        - x86_64 (amd64)
        - arm64 (aarch64)
        - Other
    validations:
      required: true

  - type: input
    id: gpg-version
    attributes:
      label: GPG Version
      description: Output of `gpg --version` (first line)
      placeholder: "gpg (GnuPG) 2.4.5"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Output
      description: |
        Paste any relevant error messages or logs.
        This will be automatically formatted as code.
      render: shell
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem.
    validations:
      required: false
